### ISSUE TITLE
Sharing through FB Messenger 

### ISSUE THREAD

**Issue by amlew00** [quotestream/quotestream.github.io#3]
Background shows up but not the text

**Comment by amlew00** [comment]
Also happens sharing theough iMessage

**Comment by amlew00** [comment]
Actually the text is missing in all sharing formats 😬

**Comment by quotestream** [comment]
I think this is fixed in build 0.3.0 - can you confirm?

**Comment by amlew00** [comment]
Still having the sharing issue. Was able to share once... then it failed

**Comment by amlew00** [comment]
Turns out it is only certain quotes that will not share 😳

**Comment by amlew00** [comment]
Trying to replicate. Was able to share to Instagram 🎉🎉🎉

**Comment by quotestream** [comment]
okay closing
